// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9AGqMqiAochrqMmBLeMmimpdLdw5YZQ',
    appId: '1:805248036097:web:cef40e2b80e599223aff00',
    messagingSenderId: '805248036097',
    projectId: 'mynotes-jeeva',
    authDomain: 'mynotes-jeeva.firebaseapp.com',
    storageBucket: 'mynotes-jeeva.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtDtvXqjgOQI2HTfcgnq7c-ivEIzvJJZI',
    appId: '1:805248036097:android:a624995f7dc4ffe53aff00',
    messagingSenderId: '805248036097',
    projectId: 'mynotes-jeeva',
    storageBucket: 'mynotes-jeeva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBw1C85JBpGuvNypCoMEtuzz6B2Ul6Vt8',
    appId: '1:805248036097:ios:340b825cf35df2d93aff00',
    messagingSenderId: '805248036097',
    projectId: 'mynotes-jeeva',
    storageBucket: 'mynotes-jeeva.appspot.com',
    iosBundleId: 'com.makingnotes.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBw1C85JBpGuvNypCoMEtuzz6B2Ul6Vt8',
    appId: '1:805248036097:ios:1ad3b92de61b39833aff00',
    messagingSenderId: '805248036097',
    projectId: 'mynotes-jeeva',
    storageBucket: 'mynotes-jeeva.appspot.com',
    iosBundleId: 'com.makingnotes.mynotes.RunnerTests',
  );
}
